#server
server:
  port: 8887
#spring
spring:
  application:
    name: z-bike
  profiles:
    active: dev


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    intialSize: 1
    maxWait: 60000
    minId: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictionRunsMills: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


#mybatis
mybatis:
  mapper-locations: classpath:com/zwx/**/**.xml
  type-aliases-package: classpath:com.zwx.**.entity

#log
logging:
  config: classpath:logback.xml


