spring:
  datasource:
    name: test
    url: jdbc:mysql://47.93.236.80:3306/bike
    username: root
    password: AaAaAa123

  #activeMQ
  activemq:
    broker-url: tcp://47.93.236.80:61616

#springdata
  data:
    mongodb:
      uri: mongodb://47.93.236.80:27017/bike

#redis
redis:
  host: 47.93.236.80
  port: 6379
  max-idle: 5
  max-total: 10
  max-wait-millis: 3000

